### PR TITLE
Merge `boututils` into `boutdata`

### PR DESCRIPTION
**Pull request by ZedThree**
Keeps history from the standalone repo. Also imports the most commonly used bits of `boututils` into `boutdata` at the top level.

I haven't made any attempt at cleaning up the repo. Do we want to try and keep the history of boututils from the main BOUT++ repo?

### CODE REVIEW

**Comment by johnomotani** [comment]
> Do we want to try and keep the history of boututils from the main BOUT++ repo?

Could be nice if it's easy to do... Would there be conflicts/confusion of any kind when the (more recent) changes were separately merged in both the boututils repo and BOUT-dev?

**Comment by johnomotani** [comment]
I guess `setup.py` needs updating somehow to provide boututils as a module, and remove it as a dependency?

**Comment by ZedThree** [comment]
I'm hoping I'll be able to merge it all into one history without conflicts,
but we'll see

**Comment by ZedThree** [comment]
Er, good point about removing it as a dependency, but it does already
install both modules

**Comment by johnomotani** [comment]
> Er, good point about removing it as a dependency, but it does already install both modules

:+1: ... I always forget how the packaging stuff works!

Should we do anything to try and detect if an old `boututils` is installed and issue some error/warning? I don't know what would happen in that case... Apparently there isn't a good way to do it though: https://stackoverflow.com/questions/51453762/can-i-specify-conflicting-packages-with-pythons-setuptools

**Comment by ZedThree** [comment]
I was just about to make an issue about possibly merging these two repos when I found this PR again.

Any objections to me reviving this and pressing ahead?

**Comment by ZedThree** [comment]
Remembered about this PR again. Updated to both package's `master`, and moved them under `src`.

I think the separation between the two packages is mostly artificial at this point, and there's a lot of cruft in `boututils` that is probably not very useful any more. It probably makes sense to have another PR moving all the useful things directly into `boutdata`, and then re-importing them back into `boututils` with a deprecation warning or something.

**Comment by ZedThree** [comment]
I'm going to use admin privileges to merge this and tidy things up a bit in another PR

**Pull request merged**
